<!DOCTYPE html>

<html>
  <head>
  </head>

  <body>
    <h1> Study of ethnic residential segregation and health outcomes with clustering analysis in Bradford, UK </h1>
    <p>The Purpose of this file is to measure segregation by index of dissimilarity</p> 
  </body>
</html>

>Index of Dissimilarity (D):

Index of Dissimilarity represents the percentage of an area’s demographic group which is required to move to another neighborhood to achieve fully integrated area. It quantifies the proportion of one ethnic group and measures the proportion this group that would require a move to achieve an even distribution of groups across all areas. Index of Dissimilarity is calculated between 0 and 1, where the value of 0 indicates complete integration and the value of 1 indicates complete segregation. 

The `Index of Dissimilarity` is calculated mathematically as follows:

**D = 100 * 0.5 * S | Pxi/Px - Pyi/Py|**
 
Where:<br>
D  =   the index of dissimilarity for two groups being compared within a specific geographic area<br>
Pxi =   the population of group x in census tract i<br>
Px  =   the total population of group x in the overall geographic area<br>
Pyi  =   the population of group y in census tract i<br>
Py   =   the total population of group y in the overall geographic area<br>
S =   the Greek letter “sigma” indicating the summation of terms<br>

In [31]:
#Importing required dataset

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt 
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
#Loading census dataset

df_census_2021 = pd.read_csv("Dataset/Processed_Data/processed_ethnic_data_2021.csv", index_col=0)

df_census_2011 = pd.read_csv("Dataset/Processed_Data/processed_ethnic_data_2011.csv", index_col=0)

df_census_2001 = pd.read_csv("Dataset/Processed_Data/processed_ethnic_data_2001.csv", index_col=0)

In [4]:
df_census_2021.head(1)

        LSOA             LAD Output_Areas  Asian  Black  White  Others
0  E01000001  City of London    E00000001      5      3    155      13

In [5]:
df_census_2011.head(1)

        LSOA             LAD Output_Areas  Asian  Black  White  Others
0  E01000001  City of London    E00000001     12      0    350      26

In [6]:
df_census_2001.head(1)

        LSOA         LAD   geography  Asian  Black  White  Others
0  E01012305  Darlington  00EHNC0001      0      0    510      12

In [7]:
# Feature creation for all 3 census years data:

def cal_add_features (df):
    '''
    returns the value of the population of group B for 
    index of dissimilarity formul
    '''
    #Feature creation for dataset

    df['other_ethinic_b_w_o'] = df['Black'] + df['White'] + df['Others'] 
    df['other_ethinic_a_w_o'] = df['Asian'] + df['White'] + df['Others'] 
    df['other_ethinic_a_b_o'] = df['Asian'] + df['Black'] + df['Others'] 
    df['other_ethinic_a_b_w'] = df['Asian'] + df['Black'] + df['White']
    df['other_ethinic_a_o'] = df['Asian'] + df['Others']
    return df

In [8]:
df_census_2021 = cal_add_features(df_census_2021)
df_census_2011 = cal_add_features(df_census_2011)
df_census_2001 = cal_add_features(df_census_2001)

In [9]:
df_census_2001.head(2)

,LSOA,LAD,geography,Asian,Black,White,Others,other_ethinic_b_w_o,other_ethinic_a_w_o,other_ethinic_a_b_o,other_ethinic_a_b_w,other_ethinic_a_o
0,E01012305,Darlington,00EHNC0001,0,0,510,12,522,522,12,510,12
1,E01012305,Darlington,00EHNC0002,0,0,624,0,624,624,0,624,0

In [10]:
# Calculating dissimilarity in LAD

# Defining variables to hold column names

a = "Asian"
b = "Black"
w = "White"
o = "Others"
b_w_o = "other_ethinic_b_w_o"
a_w_o = "other_ethinic_a_w_o"
a_b_o = "other_ethinic_a_b_o"
a_b_w = "other_ethinic_a_b_w"

In [11]:
def cal_indexOfDissimilarity(censusYear, ethinicity, LAD):
    '''
    Returns index of dissimilarity for each district in UK
    '''
    if censusYear == '2021':
        df = df_census_2021
    elif censusYear == '2011':
        df = df_census_2011
    elif censusYear == '2001':
        df = df_census_2001
        
    #Get list of towns
    towns = list(df["LAD"].unique())

    town_D = {}  # Initialize dictionary as collector
    for town in towns:
        
        # Filter by state
        tmp = df[df["LAD"] == town]
        if ethinicity == 'Asian':
            
        # Add Index of Dissimilarity to Dictionary
            town_D[town] = 0.5 * sum(abs(tmp[a] / tmp[a].sum() - tmp[b_w_o] / tmp[b_w_o].sum())) #asian
        elif ethinicity == 'Black':
            town_D[town] = 0.5 * sum(abs(tmp[b] / tmp[b].sum() - tmp[a_w_o] / tmp[a_w_o].sum())) # black
        elif ethinicity == 'White':
            town_D[town] = 0.5 * sum(abs(tmp[w] / tmp[w].sum() - tmp[a_b_o] / tmp[a_b_o].sum())) # white
        elif ethinicity == 'Others':
            town_D[town] = 0.5 * sum(abs(tmp[o] / tmp[o].sum() - tmp[a_b_w] / tmp[a_b_w].sum())) #others
    
    index_of_dissimilarity =  round(town_D[LAD], 3)
    return index_of_dissimilarity

In [12]:
#Asian-Bradford

# To calculate Index of Dissimilarity for Bradford Census data 2021
Asian_Bradford_2021 = cal_indexOfDissimilarity('2021', 'Asian', 'Bradford')
print('Index of Dissimilarity for Bradford in 2021 (Asian) :',Asian_Bradford_2021)

# To calculate Index of Dissimilarity for Bradford Census data 2011
Asian_Bradford_2011 = cal_indexOfDissimilarity('2011', 'Asian', 'Bradford')
print('Index of Dissimilarity for Bradford in 2011 (Asian) :',Asian_Bradford_2011)

# To calculate Index of Dissimilarity for Bradford Census data 2001
Asian_Bradford_2001 = cal_indexOfDissimilarity('2001', 'Asian', 'Bradford')
print('Index of Dissimilarity for Bradford in 2001 (Asian) :',Asian_Bradford_2001)

#Black-Bradford

# To calculate Index of Dissimilarity for Bradford Census data 2021
Black_Bradford_2021 = cal_indexOfDissimilarity('2021', 'Black', 'Bradford')
print('Index of Dissimilarity for Bradford in 2021 (Black) :',Black_Bradford_2021)

# To calculate Index of Dissimilarity for Bradford Census data 2011
Black_Bradford_2011 = cal_indexOfDissimilarity('2011', 'Black', 'Bradford')
print('Index of Dissimilarity for Bradford in 2011 (Black) :',Black_Bradford_2011)

# To calculate Index of Dissimilarity for Bradford Census data 2001
Black_Bradford_2001 = cal_indexOfDissimilarity('2001', 'Black', 'Bradford')
print('Index of Dissimilarity for Bradford in 2001 (Black) :',Black_Bradford_2001)

#White-Bradford

# To calculate Index of Dissimilarity for Bradford Census data 2021
White_Bradford_2021 = cal_indexOfDissimilarity('2021', 'White', 'Bradford')
print('Index of Dissimilarity for Bradford in 2021 (White) :',White_Bradford_2021)

# To calculate Index of Dissimilarity for Bradford Census data 2011
White_Bradford_2011 = cal_indexOfDissimilarity('2011', 'White', 'Bradford')
print('Index of Dissimilarity for Bradford in 2011 (White) :',White_Bradford_2011)

# To calculate Index of Dissimilarity for Bradford Census data 2001
White_Bradford_2001 = cal_indexOfDissimilarity('2001', 'White', 'Bradford')
print('Index of Dissimilarity for Bradford in 2001 (White) :',White_Bradford_2001)

#WOthers-Bradford

# To calculate Index of Dissimilarity for Bradford Census data 2021
Others_Bradford_2021 = cal_indexOfDissimilarity('2021', 'Others', 'Bradford')
print('Index of Dissimilarity for Bradford in 2021 (Others) :',Others_Bradford_2021)

# To calculate Index of Dissimilarity for Bradford Census data 2011
Others_Bradford_2011 = cal_indexOfDissimilarity('2011', 'Others', 'Bradford')
print('Index of Dissimilarity for Bradford in 2011 (Others) :',Others_Bradford_2011)

# To calculate Index of Dissimilarity for Bradford Census data 2001
Others_Bradford_2001 = cal_indexOfDissimilarity('2001', 'Others', 'Bradford')
print('Index of Dissimilarity for Bradford in 2001 (Others) :',Others_Bradford_2001)

Index of Dissimilarity for Bradford in 2021 (Asian) : 0.661
Index of Dissimilarity for Bradford in 2011 (Asian) : 0.692
Index of Dissimilarity for Bradford in 2001 (Asian) : 0.744
Index of Dissimilarity for Bradford in 2021 (Black) : 0.479
Index of Dissimilarity for Bradford in 2011 (Black) : 0.471
Index of Dissimilarity for Bradford in 2001 (Black) : 0.518
Index of Dissimilarity for Bradford in 2021 (White) : 0.654
Index of Dissimilarity for Bradford in 2011 (White) : 0.667
Index of Dissimilarity for Bradford in 2001 (White) : 0.7
Index of Dissimilarity for Bradford in 2021 (Others) : 0.295
Index of Dissimilarity for Bradford in 2011 (Others) : 0.33
Index of Dissimilarity for Bradford in 2001 (Others) : 0.371

In [13]:
#Asian-Craven 
# To calculate Index of Dissimilarity for Craven Census data 2021
Asian_Craven_2021 = cal_indexOfDissimilarity('2021', 'Asian', 'Craven')
print('Index of Dissimilarity for Craven in 2021 (Asian) :',Asian_Craven_2021)

# To calculate Index of Dissimilarity for Craven Census data 2011
Asian_Craven_2011 = cal_indexOfDissimilarity('2011', 'Asian', 'Craven')
print('Index of Dissimilarity for Craven in 2011 (Asian) :',Asian_Craven_2011)

# To calculate Index of Dissimilarity for Craven Census data 2001
Asian_Craven_2001 = cal_indexOfDissimilarity('2001', 'Asian', 'Craven')
print('Index of Dissimilarity for Craven in 2001 (Asian) :',Asian_Craven_2001)

#Black-Craven 
# To calculate Index of Dissimilarity for Craven Census data 2021
Black_Craven_2021 = cal_indexOfDissimilarity('2021', 'Black', 'Craven')
print('Index of Dissimilarity for Craven in 2021 (Black) :',Black_Craven_2021)

# To calculate Index of Dissimilarity for Craven Census data 2011
Black_Craven_2011 = cal_indexOfDissimilarity('2011', 'Black', 'Craven')
print('Index of Dissimilarity for Craven in 2011 (Black) :',Black_Craven_2011)

# To calculate Index of Dissimilarity for Craven Census data 2001
Black_Craven_2001 = cal_indexOfDissimilarity('2001', 'Black', 'Craven')
print('Index of Dissimilarity for Craven in 2001 (Black) :',Black_Craven_2001)

#White-Craven 
# To calculate Index of Dissimilarity for Craven Census data 2021
White_Craven_2021 = cal_indexOfDissimilarity('2021', 'White', 'Craven')
print('Index of Dissimilarity for Craven in 2021 (White) :',White_Craven_2021)

# To calculate Index of Dissimilarity for Craven Census data 2011
White_Craven_2011 = cal_indexOfDissimilarity('2011', 'White', 'Craven')
print('Index of Dissimilarity for Craven in 2011 (White) :',White_Craven_2011)

# To calculate Index of Dissimilarity for Craven Census data 2001
White_Craven_2001 = cal_indexOfDissimilarity('2001', 'White', 'Craven')
print('Index of Dissimilarity for Craven in 2001 (White) :',White_Craven_2001)

#Others-Craven 
# To calculate Index of Dissimilarity for Craven Census data 2021
Others_Craven_2021 = cal_indexOfDissimilarity('2021', 'Others', 'Craven')
print('Index of Dissimilarity for Craven in 2021 (Others) :',Others_Craven_2021)

# To calculate Index of Dissimilarity for Craven Census data 2011
Others_Craven_2011 = cal_indexOfDissimilarity('2011', 'Others', 'Craven')
print('Index of Dissimilarity for Craven in 2011 (Others) :',Others_Craven_2011)

# To calculate Index of Dissimilarity for Craven Census data 2001
Others_Craven_2001 = cal_indexOfDissimilarity('2001', 'Others', 'Craven')
print('Index of Dissimilarity for Craven in 2001 (Others) :',Others_Craven_2001)

Index of Dissimilarity for Craven in 2021 (Asian) : 0.593
Index of Dissimilarity for Craven in 2011 (Asian) : 0.631
Index of Dissimilarity for Craven in 2001 (Asian) : 0.868
Index of Dissimilarity for Craven in 2021 (Black) : 0.738
Index of Dissimilarity for Craven in 2011 (Black) : 0.807
Index of Dissimilarity for Craven in 2001 (Black) : 0.927
Index of Dissimilarity for Craven in 2021 (White) : 0.427
Index of Dissimilarity for Craven in 2011 (White) : 0.506
Index of Dissimilarity for Craven in 2001 (White) : 0.606
Index of Dissimilarity for Craven in 2021 (Others) : 0.359
Index of Dissimilarity for Craven in 2011 (Others) : 0.391
Index of Dissimilarity for Craven in 2001 (Others) : 0.619

In [14]:
#Asian-Harrogate

# To calculate Index of Dissimilarity for Haarogate Census data 2021
Asian_Haarogate_2021 = cal_indexOfDissimilarity('2021', 'Asian', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2021 (Asian) :',Asian_Haarogate_2021)

# To calculate Index of Dissimilarity for Haarogate Census data 2011
Asian_Haarogate_2011 = cal_indexOfDissimilarity('2011', 'Asian', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2011 (Asian) :',Asian_Haarogate_2011)

# To calculate Index of Dissimilarity for Haarogate Census data 2001
Asian_Haarogate_2001 = cal_indexOfDissimilarity('2001', 'Asian', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2001 (Asian) :',Asian_Haarogate_2001)

#Black-Harrogate
# To calculate Index of Dissimilarity for Haarogate Census data 2021
Black_Haarogate_2021 = cal_indexOfDissimilarity('2021', 'Black', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2021 (Black) :',Black_Haarogate_2021)

# To calculate Index of Dissimilarity for Haarogate Census data 2011
Black_Haarogate_2011 = cal_indexOfDissimilarity('2011', 'Black', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2011 (Black) :',Black_Haarogate_2011)

# To calculate Index of Dissimilarity for Haarogate Census data 2001
Black_Haarogate_2001 = cal_indexOfDissimilarity('2001', 'Black', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2001 (Black) :',Black_Haarogate_2001)

#White-Harrogate
# To calculate Index of Dissimilarity for Haarogate Census data 2021
White_Haarogate_2021 = cal_indexOfDissimilarity('2021', 'White', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2021 (White) :',White_Haarogate_2021)

# To calculate Index of Dissimilarity for Haarogate Census data 2011
White_Haarogate_2011 = cal_indexOfDissimilarity('2011', 'White', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2011 (White) :',White_Haarogate_2011)

# To calculate Index of Dissimilarity for Haarogate Census data 2001
White_Haarogate_2001 = cal_indexOfDissimilarity('2001', 'White', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2001 (White) :',White_Haarogate_2001)

#Others-Harrogate
# To calculate Index of Dissimilarity for Haarogate Census data 2021
Others_Haarogate_2021 = cal_indexOfDissimilarity('2021', 'Others', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2021 (Others) :',Others_Haarogate_2021)

# To calculate Index of Dissimilarity for Haarogate Census data 2011
Others_Haarogate_2011 = cal_indexOfDissimilarity('2011', 'Others', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2011 (Others) :',Others_Haarogate_2011)

# To calculate Index of Dissimilarity for Haarogate Census data 2001
Others_Haarogate_2001 = cal_indexOfDissimilarity('2001', 'Others', 'Harrogate')
print('Index of Dissimilarity for Haarogate in 2001 (Others) :',Others_Haarogate_2001)

Index of Dissimilarity for Haarogate in 2021 (Asian) : 0.444
Index of Dissimilarity for Haarogate in 2011 (Asian) : 0.501
Index of Dissimilarity for Haarogate in 2001 (Asian) : 0.806
Index of Dissimilarity for Haarogate in 2021 (Black) : 0.601
Index of Dissimilarity for Haarogate in 2011 (Black) : 0.525
Index of Dissimilarity for Haarogate in 2001 (Black) : 0.83
Index of Dissimilarity for Haarogate in 2021 (White) : 0.329
Index of Dissimilarity for Haarogate in 2011 (White) : 0.347
Index of Dissimilarity for Haarogate in 2001 (White) : 0.457
Index of Dissimilarity for Haarogate in 2021 (Others) : 0.305
Index of Dissimilarity for Haarogate in 2011 (Others) : 0.323
Index of Dissimilarity for Haarogate in 2001 (Others) : 0.49

In [15]:
#Asian-Leeds

# To calculate Index of Dissimilarity for Leeds Census data 2021
Asian_Leeds_2021 = cal_indexOfDissimilarity('2021', 'Asian', 'Leeds')
print('Index of Dissimilarity for Leeds in 2021 (Asian) :',Asian_Leeds_2021)

# To calculate Index of Dissimilarity for Leeds Census data 2011
Asian_Leeds_2011 = cal_indexOfDissimilarity('2011', 'Asian', 'Leeds')
print('Index of Dissimilarity for Leeds in 2011 (Asian) :',Asian_Leeds_2011)

# To calculate Index of Dissimilarity for Leeds Census data 2001
Asian_Leeds_2001 = cal_indexOfDissimilarity('2001', 'Asian', 'Leeds')
print('Index of Dissimilarity for Leeds in 2001 (Asian) :',Asian_Leeds_2001)

#Blacks-Leeds
# To calculate Index of Dissimilarity for Leeds Census data 2021
Black_Leeds_2021 = cal_indexOfDissimilarity('2021', 'Black', 'Leeds')
print('Index of Dissimilarity for Leeds in 2021 (Black) :',Black_Leeds_2021)

# To calculate Index of Dissimilarity for Leeds Census data 2011
Black_Leeds_2011 = cal_indexOfDissimilarity('2011', 'Black', 'Leeds')
print('Index of Dissimilarity for Leeds in 2011 (Black) :',Black_Leeds_2011)

# To calculate Index of Dissimilarity for Leeds Census data 2001
Black_Leeds_2001 = cal_indexOfDissimilarity('2001', 'Black', 'Leeds')
print('Index of Dissimilarity for Leeds in 2001 (Black) :',Black_Leeds_2001)

#White-Leeds
# To calculate Index of Dissimilarity for Leeds Census data 2021
White_Leeds_2021 = cal_indexOfDissimilarity('2021', 'White', 'Leeds')
print('Index of Dissimilarity for Leeds in 2021 (White) :',White_Leeds_2021)

# To calculate Index of Dissimilarity for Leeds Census data 2011
White_Leeds_2011 = cal_indexOfDissimilarity('2011', 'White', 'Leeds')
print('Index of Dissimilarity for Leeds in 2011 (White) :',White_Leeds_2011)

# To calculate Index of Dissimilarity for Leeds Census data 2001
White_Leeds_2001 = cal_indexOfDissimilarity('2001', 'White', 'Leeds')
print('Index of Dissimilarity for Leeds in 2001 (White) :',White_Leeds_2001)

#Others-Leeds
# To calculate Index of Dissimilarity for Leeds Census data 2021
Others_Leeds_2021 = cal_indexOfDissimilarity('2021', 'Others', 'Leeds')
print('Index of Dissimilarity for Leeds in 2021 (Others) :',Others_Leeds_2021)

# To calculate Index of Dissimilarity for Leeds Census data 2011
Others_Leeds_2011 = cal_indexOfDissimilarity('2011', 'Others', 'Leeds')
print('Index of Dissimilarity for Leeds in 2011 (Others) :',Others_Leeds_2011)

# To calculate Index of Dissimilarity for Leeds Census data 2001
Others_Leeds_2001 = cal_indexOfDissimilarity('2001', 'Others', 'Leeds')
print('Index of Dissimilarity for Leeds in 2001 (Others) :',Others_Leeds_2001)

Index of Dissimilarity for Leeds in 2021 (Asian) : 0.512
Index of Dissimilarity for Leeds in 2011 (Asian) : 0.544
Index of Dissimilarity for Leeds in 2001 (Asian) : 0.605
Index of Dissimilarity for Leeds in 2021 (Black) : 0.556
Index of Dissimilarity for Leeds in 2011 (Black) : 0.579
Index of Dissimilarity for Leeds in 2001 (Black) : 0.636
Index of Dissimilarity for Leeds in 2021 (White) : 0.484
Index of Dissimilarity for Leeds in 2011 (White) : 0.508
Index of Dissimilarity for Leeds in 2001 (White) : 0.533
Index of Dissimilarity for Leeds in 2021 (Others) : 0.329
Index of Dissimilarity for Leeds in 2011 (Others) : 0.376
Index of Dissimilarity for Leeds in 2001 (Others) : 0.432

In [16]:
#Asian - Wakefield
# To calculate Index of Dissimilarity for Wakefield Census data 2021
Asian_Wakefield_2021 = cal_indexOfDissimilarity('2021', 'Asian', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2021 (Asian) :',Asian_Wakefield_2021)

# To calculate Index of Dissimilarity for Wakefield Census data 2011
Asian_Wakefield_2011 = cal_indexOfDissimilarity('2011', 'Asian', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2011 (Asian) :',Asian_Wakefield_2011)

# To calculate Index of Dissimilarity for Wakefield Census data 2001
Asian_Wakefield_2001 = cal_indexOfDissimilarity('2001', 'Asian', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2001 (Asian) :',Asian_Wakefield_2001)

#Black-Wakefield
# To calculate Index of Dissimilarity for Wakefield Census data 2021
Black_Wakefield_2021 = cal_indexOfDissimilarity('2021', 'Black', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2021 (Black) :',Black_Wakefield_2021)

# To calculate Index of Dissimilarity for Wakefield Census data 2011
Black_Wakefield_2011 = cal_indexOfDissimilarity('2011', 'Black', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2011 (Black) :',Black_Wakefield_2011)

# To calculate Index of Dissimilarity for Wakefield Census data 2001
Black_Wakefield_2001 = cal_indexOfDissimilarity('2001', 'Black', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2001 (Black) :',Black_Wakefield_2001)

#White-Wakefield
# To calculate Index of Dissimilarity for Wakefield Census data 2021
White_Wakefield_2021 = cal_indexOfDissimilarity('2021', 'White', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2021 (White) :',White_Wakefield_2021)

# To calculate Index of Dissimilarity for Wakefield Census data 2011
White_Wakefield_2011 = cal_indexOfDissimilarity('2011', 'White', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2011 (White) :',White_Wakefield_2011)

# To calculate Index of Dissimilarity for Wakefield Census data 2001
White_Wakefield_2001 = cal_indexOfDissimilarity('2001', 'White', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2001 (White) :',White_Wakefield_2001)

#Others-Wakefield
# To calculate Index of Dissimilarity for Wakefield Census data 2021
Others_Wakefield_2021 = cal_indexOfDissimilarity('2021', 'Others', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2021 (Others) :',Others_Wakefield_2021)

# To calculate Index of Dissimilarity for Wakefield Census data 2011
Others_Wakefield_2011 = cal_indexOfDissimilarity('2011', 'Others', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2011 (Others) :',Others_Wakefield_2011)

# To calculate Index of Dissimilarity for Wakefield Census data 2001
Others_Wakefield_2001 = cal_indexOfDissimilarity('2001', 'Others', 'Wakefield')
print('Index of Dissimilarity for Wakefield in 2001 (Others) :',Others_Wakefield_2001)

Index of Dissimilarity for Wakefield in 2021 (Asian) : 0.577
Index of Dissimilarity for Wakefield in 2011 (Asian) : 0.582
Index of Dissimilarity for Wakefield in 2001 (Asian) : 0.713
Index of Dissimilarity for Wakefield in 2021 (Black) : 0.55
Index of Dissimilarity for Wakefield in 2011 (Black) : 0.57
Index of Dissimilarity for Wakefield in 2001 (Black) : 0.879
Index of Dissimilarity for Wakefield in 2021 (White) : 0.451
Index of Dissimilarity for Wakefield in 2011 (White) : 0.469
Index of Dissimilarity for Wakefield in 2001 (White) : 0.546
Index of Dissimilarity for Wakefield in 2021 (Others) : 0.348
Index of Dissimilarity for Wakefield in 2011 (Others) : 0.378
Index of Dissimilarity for Wakefield in 2001 (Others) : 0.548

In [17]:
# create an Empty DataFrame object

df_IOD = pd.DataFrame(columns = ['Ethnicity', 'LAD', '2021', '2011', '2001'])

print(df_IOD)

Empty DataFrame
Columns: [Ethnicity, LAD, 2021, 2011, 2001]
Index: []

In [32]:
# append rows to an empty DataFrame - Asian
df_IOD = df_IOD.append({
                        'Ethnicity' : 'Asian', 
                        'LAD' : 'Bradford', 
                        '2021' : Asian_Bradford_2021,
                        '2011' : Asian_Bradford_2011,
                        '2001' : Asian_Bradford_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Asian', 
                        'LAD' : 'Craven', 
                        '2021' : Asian_Craven_2021,
                        '2011' : Asian_Craven_2011,
                        '2001' : Asian_Craven_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Asian', 
                        'LAD' : 'Haarogate', 
                        '2021' : Asian_Haarogate_2021,
                        '2011' : Asian_Haarogate_2011,
                        '2001' : Asian_Haarogate_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Asian', 
                        'LAD' : 'Leeds', 
                        '2021' : Asian_Leeds_2021,
                        '2011' : Asian_Leeds_2011,
                        '2001' : Asian_Leeds_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Asian', 
                        'LAD' : 'Wakefield', 
                        '2021' : Asian_Wakefield_2021,
                        '2011' : Asian_Wakefield_2011,
                        '2001' : Asian_Wakefield_2001}, 
                ignore_index = True)

In [34]:
# append rows to an empty DataFrame - Black
df_IOD = df_IOD.append({
                        'Ethnicity' : 'Black', 
                        'LAD' : 'Bradford', 
                        '2021' : Black_Bradford_2021,
                        '2011' : Black_Bradford_2011,
                        '2001' : Black_Bradford_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Black', 
                        'LAD' : 'Craven', 
                        '2021' : Black_Craven_2021,
                        '2011' : Black_Craven_2011,
                        '2001' : Black_Craven_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Black', 
                        'LAD' : 'Haarogate', 
                        '2021' : Black_Haarogate_2021,
                        '2011' : Black_Haarogate_2011,
                        '2001' : Black_Haarogate_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Black', 
                        'LAD' : 'Leeds', 
                        '2021' : Black_Leeds_2021,
                        '2011' : Black_Leeds_2011,
                        '2001' : Black_Leeds_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Black', 
                        'LAD' : 'Wakefield', 
                        '2021' : Black_Wakefield_2021,
                        '2011' : Black_Wakefield_2011,
                        '2001' : Black_Wakefield_2001}, 
                ignore_index = True)

In [35]:
# append rows to an empty DataFrame - White
df_IOD = df_IOD.append({
                        'Ethnicity' : 'White', 
                        'LAD' : 'Bradford', 
                        '2021' : White_Bradford_2021,
                        '2011' : White_Bradford_2011,
                        '2001' : White_Bradford_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'White', 
                        'LAD' : 'Craven', 
                        '2021' : White_Craven_2021,
                        '2011' : White_Craven_2011,
                        '2001' : White_Craven_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'White', 
                        'LAD' : 'Haarogate', 
                        '2021' : White_Haarogate_2021,
                        '2011' : White_Haarogate_2011,
                        '2001' : White_Haarogate_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'White', 
                        'LAD' : 'Leeds', 
                        '2021' : White_Leeds_2021,
                        '2011' : White_Leeds_2011,
                        '2001' : White_Leeds_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'White', 
                        'LAD' : 'Wakefield', 
                        '2021' : White_Wakefield_2021,
                        '2011' : White_Wakefield_2011,
                        '2001' : White_Wakefield_2001}, 
                ignore_index = True)

In [36]:
# append rows to an empty DataFrame - Others
df_IOD = df_IOD.append({
                        'Ethnicity' : 'Others', 
                        'LAD' : 'Bradford', 
                        '2021' : Others_Bradford_2021,
                        '2011' : Others_Bradford_2011,
                        '2001' : Others_Bradford_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Others', 
                        'LAD' : 'Craven', 
                        '2021' : Others_Craven_2021,
                        '2011' : Others_Craven_2011,
                        '2001' : Others_Craven_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Others', 
                        'LAD' : 'Haarogate', 
                        '2021' : Others_Haarogate_2021,
                        '2011' : Others_Haarogate_2011,
                        '2001' : Others_Haarogate_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Others', 
                        'LAD' : 'Leeds', 
                        '2021' : Others_Leeds_2021,
                        '2011' : Others_Leeds_2011,
                        '2001' : Others_Leeds_2001}, 
                ignore_index = True)

df_IOD = df_IOD.append({
                        'Ethnicity' : 'Others', 
                        'LAD' : 'Wakefield', 
                        '2021' : Others_Wakefield_2021,
                        '2011' : Others_Wakefield_2011,
                        '2001' : Others_Wakefield_2001}, 
                ignore_index = True)

In [22]:
df_IOD.style.bar(subset=['2001','2011','2021'], color='#5fd6d6').format({"year_2001": "{:1,.f}"})

<div class="alert alert-block alert-info">
<b>Insight:</b> The table shows that for Bradford, segregation is high for Asian and White ethnic group.
Other ethnic group and black shows integration rather than segregation. 
As per 2021 census tract, Asians have 0.66 (or 66%) score which is quite high in the scale of 0 to 1 (0 to 100), reflecting a high level of ethnic separation requiring that 66% of Asians must move to achieve full integration.
Similarily, White has index of 0.65 (or 65%) which indicates 65% of White must move to other district to achieve full integration. Black and Other ethnic groups have score of 0.47 and 0.29 which indicates they are living in a quite integrated neighbourhood.
    
Noticeably, ethnic residential segregation has reduced for all the ethnic groups in comparison to last two-year census data 2011 and 2001. 
</div>

In [23]:
df_IOD.to_csv("Dataset/Processed_Data/Index_of_dissimilarity_df.csv")